[project]
title = "lsst_survey_sim"
copyright = "2023 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://lsst-survey-sim.lsst.io"
github_url = "https://github.com/lsst/lsst_survey_sim"

[project.python]
package="lsst_survey_sim"

[sphinx]
extensions = ["sphinx.ext.viewcode", "sphinx.ext.autodoc", "sphinx.ext.autosummary"]